name: CD

on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
    branches: [ main ]

jobs:
  
  deploy:
    runs-on: windows-latest

    steps:
      
      # Prepare
      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Get sources
        uses: actions/checkout@v3

      # Build and Deploy

      - name: Build Release
        run: dotnet build -c Release

      - name: Publish to Production
        run: dotnet publish -c Release --no-build --no-self-contained /p:PublishProfile=Production.pubxml /p:Password="${{ secrets.DEPLOY_PASSWORD_PRODUCTION }}"
