name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      
      # Prepare
      - name: Get sources
        uses: actions/checkout@v3

      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      # Build and Test
      - name: Build Debug
        run: dotnet build -c Debug

      - name: Run tests
        run: dotnet test --no-build --collect "Code Coverage"

      # Build
      - name: Build Release
        run: dotnet build -c Release
